# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trivy

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    # Runs at 06 PM UTC
    - cron: '0 18 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup the env
        run: |
          echo "$(make -s log | grep IMAGE)" >> "$GITHUB_ENV"
          echo "$(make -s log | grep VEX_URL)" >> "$GITHUB_ENV"
          echo "$(make -s log | grep VEX_JSON)" >> "$GITHUB_ENV"
          echo "$(make -s log | grep SEVERITY)" >> "$GITHUB_ENV"

      - name: Get rancher openvex report
        uses: wei/wget@v1
        with:
          args: -q -O ${{ env.VEX_JSON }} ${{ env.VEX_URL }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.32.0
        env:
            TRIVY_VEX: ${{ env.VEX_JSON }}
        with:
          image-ref: ${{ env.IMAGE }} 
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: ${{ env.SEVERITY }}

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

